layout_spectrum: 0.410401
typography_spectrum: 0.5288221
color:
  lightness: 0.495167
  brandStrength: 0.9755009
  saturation: 0.5933584
  rhythmicContrast: 0.7482288
  brandColors:
    - '#FF6D22'
    - '#163143'
    - '#2FBDA2'
    - '#BE9144'
    - '#267372'
name: Www.centershifting.com
